name: build

on: [push, pull_request]

env:
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  test:
    name: Test - ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        env:
          UV_PYTHON: "python${{ matrix.python-version }}"
        run: |
          uv sync --frozen --no-sources

      - name: Run tests
        run: uv run invoke tests

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate links in Markdown files
        uses: JustinBeckwith/linkinator-action@v1
        with:
          retry: true

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        env:
          UV_PYTHON: "python3.9"
        run: |
          uv sync --frozen --no-sources

      - name: Run linters
        run: uv run invoke lint --diff

  deploy:
    name: Deploy
    environment: Deployment
    needs: [test, lint]
    runs-on: ubuntu-latest
    if: github.ref=='refs/heads/main' && github.event_name!='pull_request'

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Check release
        id: check_release
        run: |
          uvx --with 'autopub[github]' autopub check

      - name: Publish
        if: ${{ steps.check_release.outputs.autopub_release=='true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          uvx --with 'autopub[github]' autopub prepare
          uvx --with 'autopub[github]' autopub commit
          uvx --with 'autopub[github]' autopub build
          uvx --with 'autopub[github]' autopub githubrelease

      - name: Upload package to PyPI
        if: ${{ steps.check_release.outputs.autopub_release=='true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
